# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buildfirmware.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62uildfirmware.proto\x12\x14\x62uildFirmwarePackage\"/\n\rNeuralNetwork\x12\r\n\x05Nodes\x18\x01 \x01(\t\x12\x0f\n\x07Weights\x18\x02 \x01(\t\"\xc3\x01\n\x14\x42uildFirmwareRequest\x12\x13\n\x0bprojectName\x18\x01 \x01(\t\x12\x12\n\nhlsToolkit\x18\x02 \x01(\t\x12\x13\n\x0btargetBoard\x18\x03 \x01(\t\x12\x0f\n\x07nInputs\x18\x04 \x01(\x05\x12\x10\n\x08nOutputs\x18\x05 \x01(\x05\x12\x0e\n\x06\x66lavor\x18\x06 \x01(\t\x12:\n\rneuralNetwork\x18\x07 \x01(\x0b\x32#.buildFirmwarePackage.NeuralNetwork\"9\n\x15\x42uildFirmwareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x13\x42uildFirmwareServer\x12j\n\rbuildFirmware\x12*.buildFirmwarePackage.BuildFirmwareRequest\x1a+.buildFirmwarePackage.BuildFirmwareResponse\"\x00\x62\x06proto3')



_NEURALNETWORK = DESCRIPTOR.message_types_by_name['NeuralNetwork']
_BUILDFIRMWAREREQUEST = DESCRIPTOR.message_types_by_name['BuildFirmwareRequest']
_BUILDFIRMWARERESPONSE = DESCRIPTOR.message_types_by_name['BuildFirmwareResponse']
NeuralNetwork = _reflection.GeneratedProtocolMessageType('NeuralNetwork', (_message.Message,), {
  'DESCRIPTOR' : _NEURALNETWORK,
  '__module__' : 'buildfirmware_pb2'
  # @@protoc_insertion_point(class_scope:buildFirmwarePackage.NeuralNetwork)
  })
_sym_db.RegisterMessage(NeuralNetwork)

BuildFirmwareRequest = _reflection.GeneratedProtocolMessageType('BuildFirmwareRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDFIRMWAREREQUEST,
  '__module__' : 'buildfirmware_pb2'
  # @@protoc_insertion_point(class_scope:buildFirmwarePackage.BuildFirmwareRequest)
  })
_sym_db.RegisterMessage(BuildFirmwareRequest)

BuildFirmwareResponse = _reflection.GeneratedProtocolMessageType('BuildFirmwareResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDFIRMWARERESPONSE,
  '__module__' : 'buildfirmware_pb2'
  # @@protoc_insertion_point(class_scope:buildFirmwarePackage.BuildFirmwareResponse)
  })
_sym_db.RegisterMessage(BuildFirmwareResponse)

_BUILDFIRMWARESERVER = DESCRIPTOR.services_by_name['BuildFirmwareServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEURALNETWORK._serialized_start=45
  _NEURALNETWORK._serialized_end=92
  _BUILDFIRMWAREREQUEST._serialized_start=95
  _BUILDFIRMWAREREQUEST._serialized_end=290
  _BUILDFIRMWARERESPONSE._serialized_start=292
  _BUILDFIRMWARERESPONSE._serialized_end=349
  _BUILDFIRMWARESERVER._serialized_start=352
  _BUILDFIRMWARESERVER._serialized_end=481
# @@protoc_insertion_point(module_scope)
