# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buildfirmware_pb2 as buildfirmware__pb2


class BuildFirmwareServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.buildFirmware = channel.unary_unary(
                '/buildFirmwarePackage.BuildFirmwareServer/buildFirmware',
                request_serializer=buildfirmware__pb2.BuildFirmwareRequest.SerializeToString,
                response_deserializer=buildfirmware__pb2.BuildFirmwareResponse.FromString,
                )


class BuildFirmwareServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def buildFirmware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildFirmwareServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'buildFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.buildFirmware,
                    request_deserializer=buildfirmware__pb2.BuildFirmwareRequest.FromString,
                    response_serializer=buildfirmware__pb2.BuildFirmwareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buildFirmwarePackage.BuildFirmwareServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuildFirmwareServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def buildFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/buildFirmwarePackage.BuildFirmwareServer/buildFirmware',
            buildfirmware__pb2.BuildFirmwareRequest.SerializeToString,
            buildfirmware__pb2.BuildFirmwareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
