# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .bond_pb2 import *


class BondServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.load = channel.unary_unary(
                '/bondPackage.BondServer/load',
                request_serializer=LoadRequest.SerializeToString,
                response_deserializer=LoadResponse.FromString,
                )
        self.predict = channel.unary_unary(
                '/bondPackage.BondServer/predict',
                request_serializer=InputRequest.SerializeToString,
                response_deserializer=InputResponse.FromString,
                )


class BondServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BondServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'load': grpc.unary_unary_rpc_method_handler(
                    servicer.load,
                    request_deserializer=LoadRequest.FromString,
                    response_serializer=LoadResponse.SerializeToString,
            ),
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=InputRequest.FromString,
                    response_serializer=InputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bondPackage.BondServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BondServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bondPackage.BondServer/load',
            LoadRequest.SerializeToString,
            LoadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bondPackage.BondServer/predict',
            InputRequest.SerializeToString,
            InputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
